//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CleanValue()
        {
            this.Point = new HashSet<Point>();
        }
    
        public int id { get; set; }
        public float frequency1 { get; set; }
        public float frequency2 { get; set; }
        public float frequency3 { get; set; }
        public float frequency4 { get; set; }
        public float frequency5 { get; set; }
        public float frequency6 { get; set; }
        public float frequency7 { get; set; }
        public float frequency8 { get; set; }
        public float frequency9 { get; set; }
        public float frequency10 { get; set; }
        public float frequency11 { get; set; }
        public float frequency12 { get; set; }
        public float frequency13 { get; set; }
        public float frequency14 { get; set; }
        public float frequency15 { get; set; }
        public float frequency16 { get; set; }
        public float frequency17 { get; set; }
        public float frequency18 { get; set; }
        public float frequency19 { get; set; }
        public float frequency20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Point { get; set; }
    }
}
