//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlPoints()
        {
            this.History = new HashSet<History>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> point_id { get; set; }
        public int premises_id { get; set; }
        public string description { get; set; }
        public string level_description { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Premises Premises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
    }
}
