//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class courseworkdbEntities : DbContext
    {
        public courseworkdbEntities()
            : base("name=courseworkdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Premises> Premises { get; set; }
        public virtual DbSet<CleanValue> CleanValue { get; set; }
        public virtual DbSet<ControlPoints> ControlPoints { get; set; }
        public virtual DbSet<NoiseValue> NoiseValue { get; set; }
        public virtual DbSet<Point> Point { get; set; }
    }
}
